title: Atomic 
subtitle: Search Solutions
email: 
description: We bring people together.
baseurl: "/widget-demo"
url: 'https://catsone.github.io'
author:
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: (123) 456-7890

# homepage tiles
tiles-source: pages 
tiles-count: 3

# social settings
500px_url:
facebook_url:
github_url: https://github.com/catsone/widget-demo
gitlab_url: 
googleplus_url:
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: https://twitter.com/catsone

# build settings
markdown: kramdown

sass:
  style: compressed
